# Generated by Django 5.2.8 on 2025-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='storage_type',
            field=models.CharField(choices=[('cloudinary', 'Cloudinary'), ('local', 'Local')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='original_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
